
import 'package:flutter/material.dart';
import 'package:mhealthapp/screens/exercise_lib/exercise%20pages/create_workout_own.dart';
import 'package:mhealthapp/screens/exercise_lib/exercise%20pages/generate_AI_workout.dart';

class CreateWorkoutPage extends StatelessWidget {
  const CreateWorkoutPage({super.key});

  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    final horizontalPadding = screenWidth * 0.08;

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: appBar(),
      bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,
        selectedItemColor: Colors.black,
        unselectedItemColor: Colors.black,
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
          BottomNavigationBarItem(icon: Icon(Icons.chat), label: 'Chat'),
          BottomNavigationBarItem(icon: Icon(Icons.list), label: 'Exercise'),
          BottomNavigationBarItem(icon: Icon(Icons.bar_chart), label: 'Activity'),
        ],
      ),
      body: Padding(
        padding: EdgeInsets.symmetric(horizontal: horizontalPadding),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 16),
            IconButton(
              icon: const Icon(Icons.arrow_back),
              onPressed: () => Navigator.pop(context),
            ),
            const SizedBox(height: 16),

            const Text(
              'Build Your Own Workout Routine',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(height: 4),
            const Text(
              'Create a workout routine tailored to your preferences! Choose from our library of built-in exercises or include your own custom exercises to build a routine that fits your goals, schedule, and favorite activities.',
              style: TextStyle(fontSize: 14),
            ),
            const SizedBox(height: 4),
            GestureDetector(
              onTap: () {
                Navigator.push(context, MaterialPageRoute(
                  builder: (context) => const BuildRoutinePage(),
                )
                );
              },
              child: const Text(
                '+ Build Routine',
                style: TextStyle(
                  fontSize: 14,
                  color: Color(0xFF6B578C),
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
            const SizedBox(height: 24),

            const Text(
              'Generate Custom Routine (AI-Powered)',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(height: 4),
            const Text(
              'Let our AI design a personalized routine for you! Answer a few quick questions and get a custom routine generated by our AI based on your fitness level, goals, and exercise history—ready to use right away.',
              style: TextStyle(fontSize: 14),
            ),
            const SizedBox(height: 4),
            GestureDetector(
              onTap: () {
                showDialog(
                  context: context,
                  builder: (context) => const GenerateAIRoutinePopup(),
                 );
              },
              child: const Text(
                '+ Generate Routine',
                style: TextStyle(
                  fontSize: 14,
                  color: Color(0xFF6B578C),
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}





AppBar appBar() {
  return AppBar(backgroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
        leading: const Padding(
          padding: EdgeInsets.only(left: 16.0),
          child: Icon(Icons.emoji_events, color: Color(0xFF6B578C), size: 48),
        ),
        title: const Text(
          'mHealth',
          style: TextStyle(
            color: Colors.black,
            fontWeight: FontWeight.w700,
            fontSize: 24,
          ),
        ),
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 16.0),
            child: IconButton(
              icon: const Icon(Icons.settings, color: Color(0xFF6B578C), size: 48),
              onPressed: () {
                
              },
            ),
          ),
        ],

  );
}
